from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    
    FINANCIAL_DATASET_API_KEY: str = ...
    OPENAI_API_KEY: str = ...
    TAVILY_API_KEY: str = ...
    
    GOOGLE_APPLICATION_CREDENTIALS: str = ...

    QDRANT_URL: str = ...
    QDRANT_API_KEY: str = ...

    GCP_PROJECT_ID: str = ...
    GCP_LOCATION: str = ...
    GCP_PROCESSOR_ID: str = ...
    GCP_PROCESSOR_VERSION: str = ...

    class Config:
        env_file = ".env.prod"
        case_sensitive = True

env_settings = Settings()
